package jadx.gui.utils.elf;

/**
 * Holds the values of various constants used in the parsing of ELF files.
 *
 * These are largely taken from include/elf/common.h of the binutils project.
 */
@SuppressWarnings("constantName") // symbol names should match those from binutils
public class ElfConstants {

	// OS ABIs
	static final int ELFOSABI_NONE = 0; /* UNIX System V ABI */
	static final int ELFOSABI_HPUX = 1; /* HP-UX operating system */
	static final int ELFOSABI_NETBSD = 2; /* NetBSD */
	static final int ELFOSABI_GNU = 3; /* GNU */
	static final int ELFOSABI_LINUX = 3; /* Alias for ELFOSABI_GNU */
	static final int ELFOSABI_SOLARIS = 6; /* Solaris */
	static final int ELFOSABI_AIX = 7; /* AIX */
	static final int ELFOSABI_IRIX = 8; /* IRIX */
	static final int ELFOSABI_FREEBSD = 9; /* FreeBSD */
	static final int ELFOSABI_TRU64 = 10; /* TRU64 UNIX */
	static final int ELFOSABI_MODESTO = 11; /* Novell Modesto */
	static final int ELFOSABI_OPENBSD = 12; /* OpenBSD */
	static final int ELFOSABI_OPENVMS = 13; /* OpenVMS */
	static final int ELFOSABI_NSK = 14; /* Hewlett-Packard Non-Stop Kernel */
	static final int ELFOSABI_AROS = 15; /* AROS */
	static final int ELFOSABI_FENIXOS = 16; /* FenixOS */
	static final int ELFOSABI_CLOUDABI = 17; /* Nuxi CloudABI */
	static final int ELFOSABI_OPENVOS = 18; /* Stratus Technologies OpenVOS */
	static final int ELFOSABI_CUDA = 51; /* NVIDIA CUDA architecture. */
	static final int ELFOSABI_C6000_ELFABI = 64; /* Bare-metal TMS320C6000 */
	static final int ELFOSABI_AMDGPU_HSA = 64; /* AMD HSA Runtime */
	static final int ELFOSABI_C6000_LINUX = 65; /* Linux TMS320C6000 */
	static final int ELFOSABI_AMDGPU_PAL = 65; /* AMD PAL Runtime */
	static final int ELFOSABI_ARM_FDPIC = 65; /* ARM FDPIC */
	static final int ELFOSABI_AMDGPU_MESA3D = 66; /* AMD Mesa3D Runtime */
	static final int ELFOSABI_ARM = 97; /* ARM */
	static final int ELFOSABI_STANDALONE = 255; /* Standalone (embedded) application */

	// types (e_type)
	static final int ET_NONE = 0; /* No file type */
	static final int ET_REL = 1; /* Relocatable file */
	static final int ET_EXEC = 2; /* Position-dependent executable file */
	static final int ET_DYN = 3; /* Position-independent executable or shared object file */
	static final int ET_CORE = 4; /* Core file */

	// architecture values
	static final int EM_NONE = 0; /* No machine */
	static final int EM_M32 = 1; /* AT&T WE 32100 */
	static final int EM_SPARC = 2; /* SUN SPARC */
	static final int EM_386 = 3; /* Intel 80386 */
	static final int EM_68K = 4; /* Motorola m68k family */
	static final int EM_88K = 5; /* Motorola m88k family */
	static final int EM_IAMCU = 6; /* Intel MCU */
	static final int EM_860 = 7; /* Intel 80860 */
	static final int EM_MIPS = 8; /* MIPS R3000 (officially, big-endian only) */
	static final int EM_S370 = 9; /* IBM System/370 */
	static final int EM_MIPS_RS3_LE = 10; /* MIPS R3000 little-endian (Oct 4 1999 Draft). Deprecated. */
	static final int EM_OLD_SPARCV9 = 11; /* Old version of Sparc v9, from before the ABI. Deprecated. */
	static final int EM_res011 = 11; /* Reserved */
	static final int EM_res012 = 12; /* Reserved */
	static final int EM_res013 = 13; /* Reserved */
	static final int EM_res014 = 14; /* Reserved */
	static final int EM_PARISC = 15; /* HPPA */
	static final int EM_res016 = 16; /* Reserved */
	static final int EM_PPC_OLD = 17; /* Old version of PowerPC. Deprecated. */
	static final int EM_VPP550 = 17; /* Fujitsu VPP500 */
	static final int EM_SPARC32PLUS = 18; /* Sun's "v8plus" */
	static final int EM_960 = 19; /* Intel 80960 */
	static final int EM_PPC = 20; /* PowerPC */
	static final int EM_PPC64 = 21; /* 64-bit PowerPC */
	static final int EM_S390 = 22; /* IBM S/390 */
	static final int EM_SPU = 23; /* Sony/Toshiba/IBM SPU */
	static final int EM_res024 = 24; /* Reserved */
	static final int EM_res025 = 25; /* Reserved */
	static final int EM_res026 = 26; /* Reserved */
	static final int EM_res027 = 27; /* Reserved */
	static final int EM_res028 = 28; /* Reserved */
	static final int EM_res029 = 29; /* Reserved */
	static final int EM_res030 = 30; /* Reserved */
	static final int EM_res031 = 31; /* Reserved */
	static final int EM_res032 = 32; /* Reserved */
	static final int EM_res033 = 33; /* Reserved */
	static final int EM_res034 = 34; /* Reserved */
	static final int EM_res035 = 35; /* Reserved */
	static final int EM_V800 = 36; /* NEC V800 series */
	static final int EM_FR20 = 37; /* Fujitsu FR20 */
	static final int EM_RH32 = 38; /* TRW RH32 */
	static final int EM_MCORE = 39; /* Motorola M*Core */ /* May also be taken by Fujitsu MMA */
	static final int EM_RCE = 39; /* Old name for MCore */
	static final int EM_ARM = 40; /* ARM */
	static final int EM_OLD_ALPHA = 41; /* Digital Alpha */
	static final int EM_SH = 42; /* Renesas (formerly Hitachi) / SuperH SH */
	static final int EM_SPARCV9 = 43; /* SPARC v9 64-bit */
	static final int EM_TRICORE = 44; /* Siemens Tricore embedded processor */
	static final int EM_ARC = 45; /* ARC Cores */
	static final int EM_H8_300 = 46; /* Renesas (formerly Hitachi) H8/300 */
	static final int EM_H8_300H = 47; /* Renesas (formerly Hitachi) H8/300H */
	static final int EM_H8S = 48; /* Renesas (formerly Hitachi) H8S */
	static final int EM_H8_500 = 49; /* Renesas (formerly Hitachi) H8/500 */
	static final int EM_IA_64 = 50; /* Intel IA-64 Processor */
	static final int EM_MIPS_X = 51; /* Stanford MIPS-X */
	static final int EM_COLDFIRE = 52; /* Motorola Coldfire */
	static final int EM_68HC12 = 53; /* Motorola M68HC12 */
	static final int EM_MMA = 54; /* Fujitsu Multimedia Accelerator */
	static final int EM_PCP = 55; /* Siemens PCP */
	static final int EM_NCPU = 56; /* Sony nCPU embedded RISC processor */
	static final int EM_NDR1 = 57; /* Denso NDR1 microprocessor */
	static final int EM_STARCORE = 58; /* Motorola Star*Core processor */
	static final int EM_ME16 = 59; /* Toyota ME16 processor */
	static final int EM_ST100 = 60; /* STMicroelectronics ST100 processor */
	static final int EM_TINYJ = 61; /* Advanced Logic Corp. TinyJ embedded processor */
	static final int EM_X86_64 = 62; /* Advanced Micro Devices X86-64 processor */
	static final int EM_PDSP = 63; /* Sony DSP Processor */
	static final int EM_PDP10 = 64; /* Digital Equipment Corp. PDP-10 */
	static final int EM_PDP11 = 65; /* Digital Equipment Corp. PDP-11 */
	static final int EM_FX66 = 66; /* Siemens FX66 microcontroller */
	static final int EM_ST9PLUS = 67; /* STMicroelectronics ST9+ 8/16 bit microcontroller */
	static final int EM_ST7 = 68; /* STMicroelectronics ST7 8-bit microcontroller */
	static final int EM_68HC16 = 69; /* Motorola MC68HC16 Microcontroller */
	static final int EM_68HC11 = 70; /* Motorola MC68HC11 Microcontroller */
	static final int EM_68HC08 = 71; /* Motorola MC68HC08 Microcontroller */
	static final int EM_68HC05 = 72; /* Motorola MC68HC05 Microcontroller */
	static final int EM_SVX = 73; /* Silicon Graphics SVx */
	static final int EM_ST19 = 74; /* STMicroelectronics ST19 8-bit cpu */
	static final int EM_VAX = 75; /* Digital VAX */
	static final int EM_CRIS = 76; /* Axis Communications 32-bit embedded processor */
	static final int EM_JAVELIN = 77; /* Infineon Technologies 32-bit embedded cpu */
	static final int EM_FIREPATH = 78; /* Element 14 64-bit DSP processor */
	static final int EM_ZSP = 79; /* LSI Logic's 16-bit DSP processor */
	static final int EM_MMIX = 80; /* Donald Knuth's educational 64-bit processor */
	static final int EM_HUANY = 81; /* Harvard's machine-independent format */
	static final int EM_PRISM = 82; /* SiTera Prism */
	static final int EM_AVR = 83; /* Atmel AVR 8-bit microcontroller */
	static final int EM_FR30 = 84; /* Fujitsu FR30 */
	static final int EM_D10V = 85; /* Mitsubishi D10V */
	static final int EM_D30V = 86; /* Mitsubishi D30V */
	static final int EM_V850 = 87; /* Renesas V850 (formerly NEC V850) */
	static final int EM_M32R = 88; /* Renesas M32R (formerly Mitsubishi M32R) */
	static final int EM_MN10300 = 89; /* Matsushita MN10300 */
	static final int EM_MN10200 = 90; /* Matsushita MN10200 */
	static final int EM_PJ = 91; /* picoJava */
	static final int EM_OR1K = 92; /* OpenRISC 1000 32-bit embedded processor */
	static final int EM_ARC_COMPACT = 93; /* ARC International ARCompact processor */
	static final int EM_XTENSA = 94; /* Tensilica Xtensa Architecture */
	static final int EM_SCORE_OLD = 95; /* Old Sunplus S+core7 backend magic number. Written in the absence of an ABI. */
	static final int EM_VIDEOCORE = 95; /* Alphamosaic VideoCore processor */
	static final int EM_TMM_GPP = 96; /* Thompson Multimedia General Purpose Processor */
	static final int EM_NS32K = 97; /* National Semiconductor 32000 series */
	static final int EM_TPC = 98; /* Tenor Network TPC processor */
	static final int EM_PJ_OLD = 99; /* Old value for picoJava. Deprecated. */
	static final int EM_SNP1K = 99; /* Trebia SNP 1000 processor */
	static final int EM_ST200 = 100; /* STMicroelectronics ST200 microcontroller */
	static final int EM_IP2K = 101; /* Ubicom IP2022 micro controller */
	static final int EM_MAX = 102; /* MAX Processor */
	static final int EM_CR = 103; /* National Semiconductor CompactRISC */
	static final int EM_F2MC16 = 104; /* Fujitsu F2MC16 */
	static final int EM_MSP430 = 105; /* TI msp430 micro controller */
	static final int EM_BLACKFIN = 106; /* ADI Blackfin */
	static final int EM_SE_C33 = 107; /* S1C33 Family of Seiko Epson processors */
	static final int EM_SEP = 108; /* Sharp embedded microprocessor */
	static final int EM_ARCA = 109; /* Arca RISC Microprocessor */
	static final int EM_UNICORE = 110; /* Microprocessor series from PKU-Unity Ltd. and MPRC of Peking University */
	static final int EM_EXCESS = 111; /* eXcess: 16/32/64-bit configurable embedded CPU */
	static final int EM_DXP = 112; /* Icera Semiconductor Inc. Deep Execution Processor */
	static final int EM_ALTERA_NIOS2 = 113; /* Altera Nios II soft-core processor */
	static final int EM_CRX = 114; /* National Semiconductor CRX */
	static final int EM_CR16_OLD = 115; /* Old, value for National Semiconductor CompactRISC. Deprecated. */
	static final int EM_XGATE = 115; /* Motorola XGATE embedded processor */
	static final int EM_C166 = 116; /* Infineon C16x/XC16x processor */
	static final int EM_M16C = 117; /* Renesas M16C series microprocessors */
	static final int EM_DSPIC30F = 118; /* Microchip Technology dsPIC30F Digital Signal Controller */
	static final int EM_CE = 119; /* Freescale Communication Engine RISC core */
	static final int EM_M32C = 120; /* Renesas M32C series microprocessors */
	static final int EM_res121 = 121; /* Reserved */
	static final int EM_res122 = 122; /* Reserved */
	static final int EM_res123 = 123; /* Reserved */
	static final int EM_res124 = 124; /* Reserved */
	static final int EM_res125 = 125; /* Reserved */
	static final int EM_res126 = 126; /* Reserved */
	static final int EM_res127 = 127; /* Reserved */
	static final int EM_res128 = 128; /* Reserved */
	static final int EM_res129 = 129; /* Reserved */
	static final int EM_res130 = 130; /* Reserved */
	static final int EM_TSK3000 = 131; /* Altium TSK3000 core */
	static final int EM_RS08 = 132; /* Freescale RS08 embedded processor */
	static final int EM_res133 = 133; /* Reserved */
	static final int EM_ECOG2 = 134; /* Cyan Technology eCOG2 microprocessor */
	static final int EM_SCORE = 135; /* Sunplus Score */
	static final int EM_SCORE7 = 135; /* Sunplus S+core7 RISC processor */
	static final int EM_DSP24 = 136; /* New Japan Radio (NJR) 24-bit DSP Processor */
	static final int EM_VIDEOCORE3 = 137; /* Broadcom VideoCore III processor */
	static final int EM_LATTICEMICO32 = 138; /* RISC processor for Lattice FPGA architecture */
	static final int EM_SE_C17 = 139; /* Seiko Epson C17 family */
	static final int EM_TI_C6000 = 140; /* Texas Instruments TMS320C6000 DSP family */
	static final int EM_TI_C2000 = 141; /* Texas Instruments TMS320C2000 DSP family */
	static final int EM_TI_C5500 = 142; /* Texas Instruments TMS320C55x DSP family */
	static final int EM_res143 = 143; /* Reserved */
	static final int EM_TI_PRU = 144; /* Texas Instruments Programmable Realtime Unit */
	static final int EM_res145 = 145; /* Reserved */
	static final int EM_res146 = 146; /* Reserved */
	static final int EM_res147 = 147; /* Reserved */
	static final int EM_res148 = 148; /* Reserved */
	static final int EM_res149 = 149; /* Reserved */
	static final int EM_res150 = 150; /* Reserved */
	static final int EM_res151 = 151; /* Reserved */
	static final int EM_res152 = 152; /* Reserved */
	static final int EM_res153 = 153; /* Reserved */
	static final int EM_res154 = 154; /* Reserved */
	static final int EM_res155 = 155; /* Reserved */
	static final int EM_res156 = 156; /* Reserved */
	static final int EM_res157 = 157; /* Reserved */
	static final int EM_res158 = 158; /* Reserved */
	static final int EM_res159 = 159; /* Reserved */
	static final int EM_MMDSP_PLUS = 160; /* STMicroelectronics 64bit VLIW Data Signal Processor */
	static final int EM_CYPRESS_M8C = 161; /* Cypress M8C microprocessor */
	static final int EM_R32C = 162; /* Renesas R32C series microprocessors */
	static final int EM_TRIMEDIA = 163; /* NXP Semiconductors TriMedia architecture family */
	static final int EM_QDSP6 = 164; /* QUALCOMM DSP6 Processor */
	static final int EM_8051 = 165; /* Intel 8051 and variants */
	static final int EM_STXP7X = 166; /* STMicroelectronics STxP7x family */
	static final int EM_NDS32 = 167; /* Andes Technology compact code size embedded RISC processor family */
	static final int EM_ECOG1 = 168; /* Cyan Technology eCOG1X family */
	static final int EM_ECOG1X = 168; /* Cyan Technology eCOG1X family */
	static final int EM_MAXQ30 = 169; /* Dallas Semiconductor MAXQ30 Core Micro-controllers */
	static final int EM_XIMO16 = 170; /* New Japan Radio (NJR) 16-bit DSP Processor */
	static final int EM_MANIK = 171; /* M2000 Reconfigurable RISC Microprocessor */
	static final int EM_CRAYNV2 = 172; /* Cray Inc. NV2 vector architecture */
	static final int EM_RX = 173; /* Renesas RX family */
	static final int EM_METAG = 174; /* Imagination Technologies Meta processor architecture */
	static final int EM_MCST_ELBRUS = 175; /* MCST Elbrus general purpose hardware architecture */
	static final int EM_ECOG16 = 176; /* Cyan Technology eCOG16 family */
	static final int EM_CR16 = 177; /* National Semiconductor CompactRISC 16-bit processor */
	static final int EM_ETPU = 178; /* Freescale Extended Time Processing Unit */
	static final int EM_SLE9X = 179; /* Infineon Technologies SLE9X core */
	static final int EM_L1OM = 180; /* Intel L1OM */
	static final int EM_K1OM = 181; /* Intel K1OM */
	static final int EM_INTEL182 = 182; /* Reserved by Intel */
	static final int EM_AARCH64 = 183; /* ARM 64-bit architecture */
	static final int EM_ARM184 = 184; /* Reserved by ARM */
	static final int EM_AVR32 = 185; /* Atmel Corporation 32-bit microprocessor family */
	static final int EM_STM8 = 186; /* STMicroeletronics STM8 8-bit microcontroller */
	static final int EM_TILE64 = 187; /* Tilera TILE64 multicore architecture family */
	static final int EM_TILEPRO = 188; /* Tilera TILEPro multicore architecture family */
	static final int EM_MICROBLAZE = 189; /* Xilinx MicroBlaze 32-bit RISC soft processor core */
	static final int EM_CUDA = 190; /* NVIDIA CUDA architecture */
	static final int EM_TILEGX = 191; /* Tilera TILE-Gx multicore architecture family */
	static final int EM_CLOUDSHIELD = 192; /* CloudShield architecture family */
	static final int EM_COREA_1ST = 193; /* KIPO-KAIST Core-A 1st generation processor family */
	static final int EM_COREA_2ND = 194; /* KIPO-KAIST Core-A 2nd generation processor family */
	static final int EM_ARC_COMPACT2 = 195; /* Synopsys ARCompact V2 */
	static final int EM_OPEN8 = 196; /* Open8 8-bit RISC soft processor core */
	static final int EM_RL78 = 197; /* Renesas RL78 family. */
	static final int EM_VIDEOCORE5 = 198; /* Broadcom VideoCore V processor */
	static final int EM_78K0R = 199; /* Renesas 78K0R. */
	static final int EM_56800EX = 200; /* Freescale 56800EX Digital Signal Controller (DSC) */
	static final int EM_BA1 = 201; /* Beyond BA1 CPU architecture */
	static final int EM_BA2 = 202; /* Beyond BA2 CPU architecture */
	static final int EM_XCORE = 203; /* XMOS xCORE processor family */
	static final int EM_MCHP_PIC = 204; /* Microchip 8-bit PIC(r) family */
	static final int EM_INTELGT = 205; /* Intel Graphics Technology */
	static final int EM_INTEL206 = 206; /* Reserved by Intel */
	static final int EM_INTEL207 = 207; /* Reserved by Intel */
	static final int EM_INTEL208 = 208; /* Reserved by Intel */
	static final int EM_INTEL209 = 209; /* Reserved by Intel */
	static final int EM_KM32 = 210; /* KM211 KM32 32-bit processor */
	static final int EM_KMX32 = 211; /* KM211 KMX32 32-bit processor */
	static final int EM_KMX16 = 212; /* KM211 KMX16 16-bit processor */
	static final int EM_KMX8 = 213; /* KM211 KMX8 8-bit processor */
	static final int EM_KVARC = 214; /* KM211 KVARC processor */
	static final int EM_CDP = 215; /* Paneve CDP architecture family */
	static final int EM_COGE = 216; /* Cognitive Smart Memory Processor */
	static final int EM_COOL = 217; /* Bluechip Systems CoolEngine */
	static final int EM_NORC = 218; /* Nanoradio Optimized RISC */
	static final int EM_CSR_KALIMBA = 219; /* CSR Kalimba architecture family */
	static final int EM_Z80 = 220; /* Zilog Z80 */
	static final int EM_VISIUM = 221; /* Controls and Data Services VISIUMcore processor */
	static final int EM_FT32 = 222; /* FTDI Chip FT32 high performance 32-bit RISC architecture */
	static final int EM_MOXIE = 223; /* Moxie processor family */
	static final int EM_AMDGPU = 224; /* AMD GPU architecture */
	static final int EM_RISCV = 243; /* RISC-V */
	static final int EM_LANAI = 244; /* Lanai 32-bit processor. */
	static final int EM_CEVA = 245; /* CEVA Processor Architecture Family */
	static final int EM_CEVA_X2 = 246; /* CEVA X2 Processor Family */
	static final int EM_BPF = 247; /* Linux BPF – in-kernel virtual machine. */
	static final int EM_GRAPHCORE_IPU = 248; /* Graphcore Intelligent Processing Unit */
	static final int EM_IMG1 = 249; /* Imagination Technologies */
	static final int EM_NFP = 250; /* Netronome Flow Processor. */
	static final int EM_VE = 251; /* NEC Vector Engine */
	static final int EM_CSKY = 252; /* C-SKY processor family. */
	static final int EM_ARC_COMPACT3_64 = 253; /* Synopsys ARCv2.3 64-bit */
	static final int EM_MCS6502 = 254; /* MOS Technology MCS 6502 processor */
	static final int EM_ARC_COMPACT3 = 255; /* Synopsys ARCv2.3 32-bit */
	static final int EM_KVX = 256; /* Kalray VLIW core of the MPPA processor family */
	static final int EM_65816 = 257; /* WDC 65816/65C816 */
	static final int EM_LOONGARCH = 258; /* LoongArch */
	static final int EM_KF32 = 259; /* ChipON KungFu32 */
	static final int EM_U16_U8CORE = 260; /* LAPIS nX-U16/U8 */
	static final int EM_TACHYUM = 261; /* Tachyum */
	static final int EM_56800EF = 262; /* NXP 56800EF Digital Signal Controller (DSC) */

	// symbol binding types
	static final int STB_LOCAL = 0; /* Symbol not visible outside obj */
	static final int STB_GLOBAL = 1; /* Symbol visible outside obj */
	static final int STB_WEAK = 2; /* Like globals, lower precedence */

	// symbol types
	static final int STT_NOTYPE = 0; /* Symbol type is unspecified */
	static final int STT_OBJECT = 1; /* Symbol is a data object */
	static final int STT_FUNC = 2; /* Symbol is a code object */
	static final int STT_SECTION = 3; /* Symbol associated with a section */
	static final int STT_FILE = 4; /* Symbol gives a file name */
	static final int STT_COMMON = 5; /* An uninitialised common block */
	static final int STT_TLS = 6; /* Thread local data object */
	static final int STT_RELC = 8; /* Complex relocation expression */
	static final int STT_SRELC = 9; /* Signed Complex relocation expression */

	// symbol visibility types
	static final int STV_DEFAULT = 0; /* Visibility is specified by binding type */
	static final int STV_INTERNAL = 1; /* OS specific version of STV_HIDDEN */
	static final int STV_HIDDEN = 2; /* Can only be seen inside currect component */
	static final int STV_PROTECTED = 3; /* Treat as STB_LOCAL inside current component */

}
