name: Build Artifacts

on:
  push:
    branches: [ master, build-test, build-artifacts ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Set jadx version
        run: |
          JADX_REV=$(git rev-list --count HEAD)
          JADX_VERSION="r${JADX_REV}.${GITHUB_SHA:0:7}"
          echo "JADX_VERSION=$JADX_VERSION" >> $GITHUB_ENV

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        run: ./gradlew dist -PjadxBundleType=app
        env:
          JADX_BUILD_JAVA_VERSION: 11

      - name: Save bundle artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ format('jadx-{0}', env.JADX_VERSION) }}
          path: build/jadx-*.zip
          if-no-files-found: error
          retention-days: 14
          archive: false

  build-win-bundle:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: oracle-actions/setup-java@v1
        with:
          release: 25

      - name: Print Java version
        shell: bash
        run: java -version

      - name: Set jadx version
        shell: bash
        run: |
          JADX_REV=$(git rev-list --count HEAD)
          JADX_VERSION="r${JADX_REV}.${GITHUB_SHA:0:7}"
          echo "JADX_VERSION=$JADX_VERSION" >> $GITHUB_ENV

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build NO-JRE bundle
        run: ./gradlew dist -PjadxBundleType=win-no-jre

      - name: Save Windows bundle artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ format('jadx-gui-{0}-no-jre-win', env.JADX_VERSION) }}
          path: build/distWin/jadx-gui-*.zip
          if-no-files-found: error
          retention-days: 14
          archive: false

      - name: Build JRE bundle
        run: ./gradlew dist -PbundleJRE=true -PjadxBundleType=win-jre

      - name: Save JRE bundle artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ format('jadx-gui-{0}-with-jre-win', env.JADX_VERSION) }}
          path: build/distWinWithJre/jadx-gui-*.zip
          if-no-files-found: error
          retention-days: 14
          archive: false

      # Prepare build for 'msi' bundle
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Install WiX Toolset
        run: |
          dotnet tool install wix --global --version 5.0.2
          wix extension add --global WixToolset.Util.wixext/5.0.2
          wix extension add --global WixToolset.UI.wixext/5.0.2
          wix.exe --version

      - name: Build msi bundle
        run: ./gradlew :jadx-gui:jpackage -PjadxBundleType=msi

      - name: Save msi artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ format('jadx-gui-{0}.msi', env.JADX_VERSION) }}
          path: jadx-gui/build/jpackage/jadx-gui-*.msi
          if-no-files-found: error
          retention-days: 14
          # nightly.link support only '.zip' artifacts, issue: https://github.com/oprypin/nightly.link/issues/88
          # archive: false

  build-mac-bundle:
    strategy:
      matrix:
        os: [ macos-latest, macos-15-intel ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Set jadx version
        run: |
          JADX_REV=$(git rev-list --count HEAD)
          JADX_VERSION="r${JADX_REV}.${GITHUB_SHA:0:7}"
          echo "JADX_VERSION=$JADX_VERSION" >> $GITHUB_ENV

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        run: ./gradlew distMac -PjadxBundleType=dmg

      - name: Save macOS DMG artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ format('jadx-gui-{0}-mac-{1}', env.JADX_VERSION, runner.arch) }}
          path: build/distMac/*.dmg
          if-no-files-found: error
          retention-days: 14
          # nightly.link support only '.zip' artifacts, issue: https://github.com/oprypin/nightly.link/issues/88
          # archive: false
