name: Release

on:
  push:
    tags:
      - "v*.*.*"

    branches: [ "release-test/v*.*.*" ]

# additional permissions for provided GitHub token to create new release
permissions:
  contents: write

jobs:
  build-release-win-bundle:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK
        uses: oracle-actions/setup-java@v1
        with:
          release: 25


      - name: Set jadx version
        uses: actions/github-script@v9
        with:
          script: |
            const jadxVersion = context.ref.split('/').pop().substring(1)
            core.exportVariable('JADX_VERSION', jadxVersion);

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6.2.0

      - name: Build No-JRE bundle
        run: ./gradlew dist -PjadxBundleType=win-no-jre

      - name: Save bundle artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ format('jadx-gui-{0}-win.zip', env.JADX_VERSION) }}
          path: ${{ format('build/distWin/jadx-gui-{0}-win.zip', env.JADX_VERSION) }}
          if-no-files-found: error
          retention-days: 1

      - name: Build JRE bundle
        run: ./gradlew dist -PbundleJRE=true -PjadxBundleType=win-jre

      - name: Save JRE bundle artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ format('jadx-gui-{0}-with-jre-win.zip', env.JADX_VERSION) }}
          path: ${{ format('build/distWinWithJre/jadx-gui-{0}-with-jre-win.zip', env.JADX_VERSION) }}
          if-no-files-found: error
          retention-days: 1

      # Prepare build for 'msi' bundle
      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '8.0.x'

      - name: Install WiX Toolset
        run: |
          dotnet tool install wix --global --version 5.0.2
          wix extension add --global WixToolset.Util.wixext/5.0.2
          wix extension add --global WixToolset.UI.wixext/5.0.2
          wix.exe --version

      - name: Build msi bundle
        run: ./gradlew :jadx-gui:jpackage -PjadxBundleType=msi

      - name: Save msi artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ format('jadx-gui-{0}.msi', env.JADX_VERSION) }}
          path: jadx-gui/build/jpackage/jadx-gui-*.msi
          if-no-files-found: error
          retention-days: 1

  build-release-mac-bundle:
    strategy:
      matrix:
        os: [ macos-latest, macos-15-intel ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Set jadx version
        uses: actions/github-script@v9
        with:
          script: |
            const jadxVersion = context.ref.split('/').pop().substring(1)
            core.exportVariable('JADX_VERSION', jadxVersion);

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6.2.0

      - name: Build
        run: ./gradlew distMac -PjadxBundleType=dmg

      - name: Save macOS DMG artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ format('jadx-gui-{0}-mac-{1}', env.JADX_VERSION, runner.arch) }}
          path: build/distMac/*.dmg
          if-no-files-found: error
          retention-days: 1

  release:
    needs: [ build-release-win-bundle, build-release-mac-bundle ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Set jadx version and release name
        uses: actions/github-script@v9
        with:
          script: |
            const jadxVersion = context.ref.split('/').pop().substring(1)
            core.exportVariable('JADX_VERSION', jadxVersion);

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6.2.0

      - name: Build
        run: ./gradlew dist -PjadxBundleType=app
        env:
          JADX_BUILD_JAVA_VERSION: 11

      - name: Download Windows NO-JRE bundle
        uses: actions/download-artifact@v8
        with:
          name: ${{ format('jadx-gui-{0}-win.zip', env.JADX_VERSION) }}
          path: build

      - name: Download Windows JRE bundle
        uses: actions/download-artifact@v8
        with:
          name: ${{ format('jadx-gui-{0}-with-jre-win.zip', env.JADX_VERSION) }}
          path: build

      - name: Download Windows MSI bundle
        uses: actions/download-artifact@v8
        with:
          name: ${{ format('jadx-gui-{0}.msi', env.JADX_VERSION) }}
          path: build

      - name: Download macOS DMG bundles
        uses: actions/download-artifact@v8
        with:
          pattern: ${{ format('jadx-gui-{0}-mac-*', env.JADX_VERSION) }}
          merge-multiple: true
          path: build

      - run: |
          cd build
          ls -l

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ env.JADX_VERSION }}
          draft: true
          fail_on_unmatched_files: true
          files: |
            build/jadx-*.zip
            build/jadx-gui-*.msi
            build/jadx-gui-*-mac-*.dmg
